### ISSUE TITLE
Looking forward to the code for this paper

### ISSUE THREAD

**Issue by HuiHuiSun** [clvrai/boss#1]
Hi,
 Thank you for sharing this well organized codebase!
 Looking forward to the code for this paper.

**Comment by jesbu1** [comment]
Sorry for the delay, have been extremely busy with deadlines. This will happen in feb!

**Comment by tunglm2203** [comment]
> Sorry for the delay, have been extremely busy with deadlines. This will happen in feb!

Hi @jesbu1, when do you expect to release the code for the paper?

**Comment by jesbu1** [comment]
Soon, i'm working on it. I just released the code for sprint: https://github.com/clvrai/sprint, which shares a lot of code with BOSS, if you are interested in first taking a look at that for setup.

**Comment by PrivateRyan2** [comment]
Hi, @jesbu1 
I'm eagerly looking forward to the release of the code for your BOSS paper. 
Do you have an estimated timeline for when it might be available?
Thank you.

**Comment by jesbu1** [comment]
I'm trying really hard to finish it soon, sorry, i have a bit much going on right now. My target is by the end of this month.

**Comment by jesbu1** [comment]
Just an update: the code is heavily refactored and nearly ready, but I'm having some trouble reproducing certain results due to these changes. I'm looking into this, but it will take some more time.

**Comment by RenMing-Huang** [comment]
Looking forward to the code for this amazing work!

**Comment by jesbu1** [comment]
Code has been released!
